--OPTIMIZACION DE CONSULTAS 

USE Northwind

--UTILICE LAS COLUMNAS NECESARIAS Y EVITAR EL *
--UTILICE CLAUSULAS WHERE PARA DEVOLVER SOLO FILAS NECESARIAS 
--UTILIZAR LO MENOS POSIBLE TABLAS TEMPORALES
--UTILIZAR LO MENOS POSIBLE FORMULAS QUE AFECTEN A LOS CAMPOS DE LA BASE
--TRABAJASR CON INDICES ES LO MEJOR PORQUE TE PERMITE MEJORAR LA AGRUPACION Y LA BUSQUEDA ICLUSO DE ORDENAR
--(HAY INDICES HAY AGRUPADOS(SE ORDENA FISICAMENTE EN EL DISCO) Y NO AGRUPADOS(CREA UNA ESTRUCTURA ADICIONAL LLAMADA NIVEL DE HOJA))

SELECT CUSTOMERID, COMPANYNAME, CONTACTNAME
INTO CLIENTES
FROM CUSTOMERS WHERE CUSTOMERID='ALFKI'

--CREACION DE INDICES
CREATE CLUSTERED INDEX CL_CLIENTE ON CLIENTES (CUSTOMERID)

--CONSULTA AHORA POR EL INDICE CREADO
SELECT CUSTOMERID, COMPANYNAME, CONTACTNAME
FROM CLIENTES WHERE CUSTOMERID='ALFKI'

--PARA SABER QUE CAMINO TOMO PARA OBTENER EL RESULTADO DE LA LÍNEA ANTERIOIR PODEMOS VER EN EL ICONO DE MOSTRAR PLAN DE EJECUCION
--ESTO TE MUESTRA LOS PASOS QUE HIZO EN FORMA DE ICONOS Y COMO CONDIGUIO EL RESULTADO 
--ES NECESARIO SABER QUE INTERPRETA CADA ICONO PARA TENER MEJORES OPTIMIZACIONES
--VIENDO EL ICONO ME DICE QUE HA USADO INDICE PARA TENER UNA MEJOR CONSULTA

SELECT COUNTRY, COUNT(CUSTOMERID) FROM Customers GROUP BY COUNTRY
--CUANDO SE PIDE ORDENAR O AGRUPAR UN CAMPO, EL DISCO BUSCA ORDENAR QUIZAS UN CAMPO QUE NO ESTA ORDENADO Y TOMA TIEMPO EN HACERLO
--ASÍ QUE NO ES TAN OPTIMO TOMAR ESTE PASO, LO QUE SE PODRÍA HACER ES CREAR UN INDICE



--HAY ESTADÍSTICAS QUE ESTAN DENTRO DE LOS ÍCONOS PARA SABER CUANTO EN POROPORCIONES SIRVE PARA MEJORAR LOS PASOS A TOMAR PARA OPTIOMIZAR 
--LAS CONSULTAS
